10 DATA 1, 2, 3, APPLE, "COMMODORE 64"
20 DATA ."IN-DOUBLE-QUOTES"
30 DATA "THIS ; IS : A # TEST , ISN'T IT? "
40 READ A
50 READ B%, C, D$
60 READ E$
70 READ F$, G$
80 PRINT A, B%, C, D$, E$, F$ : PRINT "("G$")"